DROP TABLE IF EXISTS `company`;
CREATE TABLE IF NOT EXISTS `company` (
  `company_id` int(10) NOT NULL AUTO_INCREMENT,
  `company_name` varchar(50) CHARACTER SET utf8 NOT NULL DEFAULT '0',
  PRIMARY KEY (`company_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

INSERT INTO `company` (`company_name`) VALUES
	('하이텍크'),
	('LG'),
	('삼성'),
	('SK'),
	('현대'),
	('한화'),
	('sktelecom'),
	('유한제지'),
	('롯데'),
	('엘지전자'),
	('유한킴벌리'),
	('CJ'),
	('명성식품'),
	('명성기업'),
	('KT'),
	('명인 철광'),
	('포스코'),
	('아마존'),
	('애플'),
	('구글'),
	('페이스북'),
	('마이크로소프트'),
	('월마트'),
	('버라이즌'),
	('토요타'),
	('케논'),
	('소니'),
	('BP'),
	('AT&T'),
	('TOTAL'),
	('COASTCO'),
	('중국은행'),
	('BMW GROUP'),
	('IBM'),
	('TESCO'),
	('SK HOLDDINGS'),
	('PHILIPS'),
	('금호 타이어'),
	('AIG');
