DROP TABLE IF EXISTS `country`;
CREATE TABLE IF NOT EXISTS `country` (
  `country_id` int(10) NOT NULL AUTO_INCREMENT,
  `country_name` varchar(50) CHARACTER SET utf8 NOT NULL DEFAULT '0',
  PRIMARY KEY (`country_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

INSERT INTO `country` (`country_name`) VALUES
	('이탈리아1'),
	('스페인'),
	('인도'),
	('한국'),
	('중국'),
	('일본'),
	('러시아'),
	('인도'),
	('미국'),
	('영국'),
	('몽골'),
	('필리핀'),
	('카자흐스탄'),
	('파키스탄'),
	('노르웨이'),
	('독일'),
	('핀란드'),
	('이탈리아'),
	('에스파냐'),
	('포르투갈'),
	('아일랜드'),
	('프랑스'),
	('체코'),
	('벨기에'),
	('우크라이나'),
	('루마니아'),
	('그리스'),
	('터키'),
	('이란'),
	('아프가니스탄'),
	('이스라엘'),
	('요르단'),
	('캐나다'),
	('그란란드'),
	('칠레'),
	('브라질'),
	('멕시코'),
	('콰테말라'),
	('아르헨티나'),
	('도미니카공화국'),
	('우루과이');
